apiVersion: serving.kserve.io/v1beta1
kind: "InferenceService"
metadata:
  name: "tfserving-cifar10"
  namespace: "kserve-test"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://seldon-models/tfserving/cifar10/resnet32"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    logger:
      mode: all
      url: http://broker-ingress.knative-eventing.svc.cluster.local/knative-eventing/knative-broker/default